// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onrgodwgfuzbriwtffbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ucmdvZHdnZnV6YnJpd3RmZmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDY5OTMsImV4cCI6MjA2MzgyMjk5M30.MWUWZq23YzySF5sVjraB4iaaNdPD0JpcjNFnTfCVs_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);